### ISSUE TITLE
An index is required, but none found

### ISSUE THREAD

**Issue by simplelive** [phenotips/variant-store#10]
10:29:40.309 [main] INFO  d.c.c.j.io.JannovarDataSerializer - Deserializing JannovarData from \data\dev-variant-store\jannovar\data\hg19_ucsc.ser
10:30:00.648 [main] INFO  d.c.c.j.io.JannovarDataSerializer - Deserialization took 20.32 sec.
Exception in thread "main" htsjdk.tribble.TribbleException: An index is required, but none found., for input source: D:\data\dev-variant-store\jannovar\vcf\P000001.jv.vcf
    at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:110)
    at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:89)
    at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:69)
    at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:50)
    at org.phenotips.variantstore.input.vcf.VCFIterator.<init>(VCFIterator.java:51)
    at org.phenotips.variantstore.VariantStore.addIndividual(VariantStore.java:72)
    at org.phenotips.variantstore.VariantStore.main(VariantStore.java:122)

**Comment by meatcar** [comment]
not using jannovar anymore.
