### ISSUE TITLE
Parse '-' ALTs in some VCFs to include the prefix base

### ISSUE THREAD

**Issue by meatcar** [phenotips/variant-store#2]
[htsjdk](https://github.com/samtools/htsjdk) can't process VCF files that have `-` in the ALT field as a way to signal deletions, and throws errors like the one below. This is because the VCF file doesn't conform to spec, and was probably generated by some annotation tool. However due to the crazy amount of such non-conforming files that are floating around, we should deal with it. We should catch the error, and pass the VCF file through a sequence of steps to make it conform to spec. The relevant part of the spec is quoted below.
### Error:

```
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 26: unparsable vcf record with allele -, for input source: VCFFILENAMEHERE.vcf
    at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:793)
    at htsjdk.variant.vcf.AbstractVCFCodec.checkAllele(AbstractVCFCodec.java:578)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseAlleles(AbstractVCFCodec.java:540)
    at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:342)
    at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:285)
    at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:263)
    at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:60)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:79)
    at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:41)
    at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:335)
    at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
    at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:276)
    at org.phenotips.variantstore.storage.ProcessSingleVCFTask.call(ProcessSingleVCFTask.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```
### VCF `v4.1` and `v4.2` Spec in Regards to Indels

> For simple insertions and deletions in which either the REF or one of the ALT alleles would otherwise be null/empty, the REF and ALT Strings must include the base before the event (which must be reflected in the POS field), unless the event occurs at position 1 on the contig in which case it must include the base after the event;

[VCF v4.2 Spec](http://samtools.github.io/hts-specs/VCFv4.2.pdf)

**Comment by meatcar** [comment]
The issue was caused by VCFs that were generated by an old version of Jannovar, and output by Exomiser. Newer revisions of Jannovar don't output shortened variants anymore, so this should stop being an issue any day now.
