### ISSUE TITLE
Ftp download throws an exception

### ISSUE THREAD

**Issue by simplelive** [phenotips/variant-store#7]
16:36:40.724 [main] INFO  d.c.c.j.d.JannovarDataFactory - Downloading http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz

[>                                                 ]   0%  
[==================================================]   100%  
16:36:41.053 [main] INFO  d.c.c.j.d.JannovarDataFactory - Downloading ftp://ftp.ncbi.nlm.nih.gov/genomes/H_sapiens/ARCHIVE/ANNOTATION_RELEASE.105/Assembled_chromosomes/chr_accessions_GRCh37.p13
15/03/24 16:36:43 ERROR variantstore.VariantStore: Error initializing VariantStore
org.phenotips.variantstore.VariantStoreException: Error fetching Jannovar data
    at org.phenotips.variantstore.JannovarController.ensureDataExists(JannovarController.java:74)
    at org.phenotips.variantstore.JannovarController.init(JannovarController.java:37)
    at org.phenotips.variantstore.VariantStore.init(VariantStore.java:54)
    at org.phenotips.variantstore.VariantStore.main(VariantStore.java:134)
Caused by: de.charite.compbio.jannovar.datasource.FileDownloadException: ERROR: problem downloading file Could not change directory to genomes\H_sapiens\ARCHIVE\ANNOTATION_RELEASE.105\Assembled_chromosomes
    at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFileWithFTP(FileDownloader.java:176)
    at de.charite.compbio.jannovar.datasource.FileDownloader.copyURLToFile(FileDownloader.java:81)
    at de.charite.compbio.jannovar.datasource.JannovarDataFactory.build(JannovarDataFactory.java:83)
    at org.phenotips.variantstore.JannovarController.ensureDataExists(JannovarController.java:68)
    ... 3 more

**Comment by simplelive** [comment]
Modify de.charite.compbio.jannovar.datasource.FileDownloader.java

Line 80

Change [ ptions.ftp.host == null ] to [ ptions.ftp.host != null ]

**Comment by meatcar** [comment]
The issue should be reported upstream to the [Jannovar project](https://github.com/charite/jannovar), probably with a pull request attached.
