### ISSUE TITLE
Hard-coded paths in the `main` method cause NoSuchFile exceptions at runtime

### ISSUE THREAD

**Issue by simplelive** [phenotips/variant-store#8]
```
# uname -a
Linux Vtwo 2.6.32-042stab094.7 #1 SMP Wed Oct 22 12:43:21 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

# java -Xmx1024M -Xms1024M  -cp variant-store-1.0-SNAPSHOT.jar:`find lib/*.jar | xargs echo | sed 's/ /:/g'` org.phenotips.variantstore.VariantStore
2015-03-25 10:27:06,907 0    [main] DEBUG org.phenotips.variantstore.VariantStore  - Starting
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/variant-store/target/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/variant-store/target/lib/jannovar-cli-0.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[==================================================]   100%
[==================================================]   100%
[==================================================]   100%
[==================================================]   100%
[==================================================]   100%
[==================================================]   100%
[==================================================]   100%
2015-03-25 10:28:07,178 60271 [main] DEBUG org.phenotips.variantstore.VariantStore  - Started
2015-03-25 10:28:07,178 60271 [main] DEBUG org.phenotips.variantstore.VariantStore  - Adding
2015-03-25 10:28:07,180 60273 [main] ERROR org.phenotips.variantstore.VariantStore  - ERROR!!
org.phenotips.variantstore.db.DatabaseException: Error copying VCF for storage.
        at org.phenotips.variantstore.input.vcf.VCFManager.addIndividual(VCFManager.java:47)
        at org.phenotips.variantstore.VariantStore.addIndividual(VariantStore.java:65)
        at org.phenotips.variantstore.VariantStore.main(VariantStore.java:121)
Caused by: java.nio.file.NoSuchFileException: /data/vcf/completegenomics/vcfBeta-HG00731-200-37-ASM.vcf.gz
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:520)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1227)
        at org.phenotips.variantstore.input.vcf.VCFManager.addIndividual(VCFManager.java:45)
        ... 2 more
Exception in thread "main" java.lang.NullPointerException
        at org.phenotips.variantstore.db.solr.SolrController.stop(SolrController.java:59)
        at org.phenotips.variantstore.VariantStore.stop(VariantStore.java:50)
        at org.phenotips.variantstore.VariantStore.main(VariantStore.java:132)
```

**Comment by sdumitriu** [comment]
That's because the `/data/` directory is hard-coded in the code, and it probably doesn't exist on your system. Try changing [`VariantStore.java`](https://github.com/phenotips/variant-store/blob/master/src/main/java/org/phenotips/variantstore/VariantStore.java#L104-L121) with a different directory.

**Comment by meatcar** [comment]
The Variant Store is not designed to be run from the command line, and is currently under heavy development. The `main()` method is effectively a single integration test that I am using to ensure that everything is working on my local instance. We'll be adding real tests, and removing the main method as soon as the interface and API stabilize.
